# -*- coding: utf-8 -*-
# File: __init__.py

# Copyright 2025 Dr. Janis Meyer. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
# dd_core: Core Data Structures for deepdoctection

This package provides the foundational data structures and utilities for the deepdoctection ecosystem.
It includes:

- **utils**: Core utility functions and helpers
- **datapoint**: Data models for annotations, bounding boxes, images, and views

This is the minimal package needed for client-side processing of deepdoctection data structures.
"""

import sys
from typing import TYPE_CHECKING

from .utils.file_utils import _LazyModule

__version__ = "1.0"

_IMPORT_STRUCTURE = {
    "dataflow": [
        "DataFlowReentrantGuard",
        "DataFlow",
        "RNGDataFlow",
        "ProxyDataFlow",
        "TestDataSpeed",
        "FlattenData",
        "MapData",
        "MapDataComponent",
        "RepeatedData",
        "ConcatData",
        "JoinData",
        "BatchData",
        "CacheData",
        "CustomDataFromList",
        "CustomDataFromIterable",
        "FileClosingIterator",
        "SerializerJsonlines",
        "SerializerTabsepFiles",
        "SerializerFiles",
        "CocoParser",
        "SerializerCoco",
        "SerializerPdfDoc",
        "MultiThreadMapData",
        "MultiProcessMapData",
        "DataFromList",
        "DataFromIterable",
        "FakeData",
        "PickleSerializer",
        "MeanFromDataFlow",
        "StdFromDataFlow",
    ],
    "datapoint": [
        "AnnotationMap",
        "Annotation",
        "CategoryAnnotation",
        "ImageAnnotation",
        "ContainerAnnotation",
        "coco_iou",
        "area",
        "intersection",
        "np_iou",
        "iou",
        "ioa",
        "BoundingBox",
        "intersection_box",
        "crop_box_from_image",
        "local_to_global_coords",
        "global_to_local_coords",
        "merge_boxes",
        "rescale_coords",
        "intersection_boxes",
        "convert_b64_to_np_array",
        "convert_np_array_to_b64",
        "convert_np_array_to_b64_b",
        "convert_bytes_to_np_array",
        "convert_pdf_bytes_to_np_array_v2",
        "convert_np_array_to_torch",
        "MetaAnnotation",
        "ImageFormats",
        "Image",
        "Text_",
        "ImageAnnotationBaseView",
        "Word",
        "Layout",
        "Cell",
        "List",
        "Table",
        "ImageDefaults",
        "IMAGE_DEFAULTS",
        "ann_obj_view_factory",
        "Page",
    ],
    "mapper": [
        "cat_to_sub_cat",
        "re_assign_cat_ids",
        "filter_cat",
        "filter_summary",
        "image_to_cat_id",
        "remove_cats",
        "add_summary",
        "coco_to_image",
        "image_to_coco",
        "image_to_d2_frcnn_training",
        "image_to_hf_detr_training",
        "DetrDataCollator",
        "image_to_raw_layoutlm_features",
        "layoutlm_features_to_pt_tensors",
        "raw_features_to_layoutlm_features",
        "LayoutLMDataCollator",
        "image_to_layoutlm_features",
        "image_to_raw_lm_features",
        "image_to_lm_features",
        "MappingContextManager",
        "DefaultMapper",
        "curry",
        "maybe_get_fake_score",
        "LabelSummarizer",
        "match_anns_by_intersection",
        "match_anns_by_distance",
        "to_image",
        "maybe_load_image",
        "maybe_remove_image",
        "maybe_remove_image_from_category",
        "image_ann_to_image",
        "maybe_ann_to_sub_image",
        "xml_to_dict",
        "batched_nms",
        "pt_nms_image_annotations",
        "pascal_voc_dict_to_image",
        "prodigy_to_image",
        "image_to_prodigy",
        "tile_table",
        "pub_to_image_uncur",
        "pub_to_image",
        "to_wandb_image",
        "xfund_to_image",
    ],
    "utils": [
        "timeout_manager",
        "SETTINGS",
        "collect_torch_env",
        "collect_env_info",
        "BoundingBoxError",
        "AnnotationError",
        "ImageError",
        "UUIDError",
        "DependencyError",
        "DataFlowTerminatedError",
        "DataFlowResetStateNotCalledError",
        "DuplicateObjectTypeError",
        "MalformedData",
        "FileExtensionError",
        "TesseractError",
        "PopplerError",
        "pytorch_available",
        "get_pytorch_requirement",
        "pyzmq_available",
        "lxml_available",
        "get_lxml_requirement",
        "apted_available",
        "get_apted_requirement",
        "distance_available",
        "get_distance_requirement",
        "networkx_available",
        "numpy_v1_available",
        "get_numpy_v1_requirement",
        "transformers_available",
        "get_transformers_requirement",
        "detectron2_available",
        "get_detectron2_requirement",
        "tesseract_available",
        "set_tesseract_path",
        "get_tesseract_version",
        "get_tesseract_requirement",
        "pdf_to_ppm_available",
        "pdf_to_cairo_available",
        "get_poppler_requirement",
        "pdfplumber_available",
        "get_pdfplumber_requirement",
        "cocotools_available",
        "get_cocotools_requirement",
        "scipy_available",
        "jdeskew_available",
        "get_jdeskew_requirement",
        "sklearn_available",
        "get_sklearn_requirement",
        "qpdf_available",
        "boto3_available",
        "get_boto3_requirement",
        "aws_available",
        "get_aws_requirement",
        "doctr_available",
        "get_doctr_requirement",
        "wandb_available",
        "get_wandb_requirement",
        "opencv_available",
        "get_opencv_requirement",
        "pillow_available",
        "get_pillow_requirement",
        "pypdfium2_available",
        "get_pypdfium2_requirement",
        "pypdf_available",
        "spacy_available",
        "get_spacy_requirement",
        "timm_available",
        "get_timm_requirement",
        "mkdir_p",
        "copy_file_to_target",
        "download",
        "load_image_from_file",
        "get_load_image_func",
        "maybe_path_or_pdf",
        "load_json",
        "is_uuid_like",
        "get_uuid_from_str",
        "get_uuid",
        "LoggingRecord",
        "logger",
        "set_logger_dir",
        "auto_set_dir",
        "get_logger_dir",
        "log_once",
        "AttrDict",
        "set_config_by_yaml",
        "save_config_to_yaml",
        "config_to_cli_str",
        "ObjectTypes",
        "object_types_registry",
        "DefaultType",
        "PageType",
        "SummaryType",
        "DocumentType",
        "LayoutType",
        "TableType",
        "CellType",
        "WordType",
        "TokenClasses",
        "BioTag",
        "TokenClassWithTag",
        "Relationships",
        "Languages",
        "DatasetType",
        "token_class_tag_to_token_class_with_tag",
        "token_class_with_tag_to_token_class_and_tag",
        "update_all_types_dict",
        "get_type",
        "update_black_list",
        "decrypt_pdf_document",
        "decrypt_pdf_document_from_bytes",
        "get_pdf_file_reader",
        "get_pdf_file_writer",
        "PDFStreamer",
        "pdf_to_np_array_poppler",
        "pdf_to_np_array_pdfmium",
        "pdf_to_np_array",
        "split_pdf",
        "load_bytes_from_pdf_file",
        "get_torch_device",
        "get_num_gpu",
        "apply_torch_image",
        "get_tqdm",
        "box_to_point4",
        "point4_to_box",
        "BaseTransform",
        "ResizeTransform",
        "InferenceResize",
        "normalize_image",
        "pad_image",
        "PadTransform",
        "RotationTransform",
        "delete_keys_from_dict",
        "split_string",
        "string_to_dict",
        "to_bool",
        "call_only_once",
        "is_file_extension",
        "partition_list",
        "draw_boxes",
        "interactive_imshow",
        "viz_handler",
    ],
}

if TYPE_CHECKING:
    from . import dataflow, datapoint, mapper, utils

sys.modules[__name__] = _LazyModule(
    __name__,
    globals()["__file__"],
    _IMPORT_STRUCTURE,
    module_spec=__spec__,
    extra_objects={"__version__": __version__, "_IMPORT_STRUCTURE": _IMPORT_STRUCTURE},
)
