# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_url: https://example.com/
site_name: deepdoctection
site_author: Dr. Janis Meyer
site_description: A Document AI package
repo_url: https://github.com/deepdoctection/deepdoctection
edit_uri: blob/main/docs

theme:
  name: material
  palette:
    primary: blue
    accent: indigo
  logo: ./tutorials/_imgs/dd_logo_only.png
  features:
    - navigation.tabs
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
    - header.autohide
    - content.tabs.link
  icon:
    annotation: material/alpha-i-circle
    admonition:
      note: fontawesome/solid/exclamation
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      example: fontawesome/solid/flask

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


nav:
    - index.md
    - install.md
    - Tutorials:
          - Get Started: ./tutorials/Analyzer_Get_Started.md
          - More On Parsing: ./tutorials/Analyzer_More_On_Parsing.md
          - Configuration: ./tutorials/Analyzer_Configuration.md
          - Configuration Samples: ./tutorials/Analyzer_Configuration_Samples.md
          - Model Registry And New Models: ./tutorials/Analyzer_Model_Registry_And_New_Models.md
          - Doclaynet With A YOLO Predictor: ./tutorials/Analyzer_Doclaynet_With_YOLO.md
          - Pipelines: ./tutorials/Pipelines.md
          - Data Structures: ./tutorials/Data_Structure.md
          - Datasets: ./tutorials/Datasets.md
          - Architecture: ./tutorials/Architecture.md
          - Evaluation: ./tutorials/Evaluation.md
          - Training And Fine Tuning: ./tutorials/Training_And_Fine_Tuning.md
    - Projects:
          - Training A Model On Several Datasets: ./tutorials/Project_Training.md
          - Custom Pipeline: ./tutorials/Custom_Pipeline.md
          - LayoutLM For Sequence Classification: ./tutorials/LayoutLM_For_Seq_Class.md
          - LayoutLM For Custom Token Classification: ./tutorials/LayoutLM_For_Custom_Token_Class.md
    - API:
        - analyzer: ./modules/deepdoctection.analyzer.md
        - dataflow: ./modules/deepdoctection.dataflow.md
        - datapoint: ./modules/deepdoctection.datapoint.md
        - datasets: ./modules/deepdoctection.datasets.md
        - datasets.instances: ./modules/deepdoctection.datasets.instances.md
        - eval: ./modules/deepdoctection.eval.md
        - extern: ./modules/deepdoctection.extern.md
        - extern.pt: ./modules/deepdoctection.extern.pt.md
        - extern.tp: ./modules/deepdoctection.extern.tp.md
        - mapper: ./modules/deepdoctection.mapper.md
        - pipe: ./modules/deepdoctection.pipe.md
        - train: ./modules/deepdoctection.train.md
        - utils: ./modules/deepdoctection.utils.md


plugins:
    - search:
        lang: en
    - mkdocstrings:
        handlers:
          python:
            options:
              line_length: 120
              docstring_style: sphinx
              merge_init_into_class: True
              heading_level: 3

# to watch lib files in mkdocs server. Uncomment, if update docs locally
watch:
    - deepdoctection
