# -*- coding: utf-8 -*-
# File: _data.py

# Copyright 2025 Dr. Janis Meyer. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


PDF_BYTES =  (
        b"%PDF-1.3\n1 0 obj\n<<\n/Type /Pages\n/Count 1\n/Kids [ 3 0 R ]\n>>\nendobj\n2 0 obj\n<<\n/Producer "
        b"(PyPDF2)\n>>\nendobj\n3 0 obj\n<<\n/Type /Page\n/Parent 1 0 R\n/Resources <<\n/Font "
        b"<<\n/F1 5 0 R\n>>\n/ProcSet 6 0 R\n>>\n/MediaBox [ 0 0 612 792 ]\n/Contents 7 0 R\n>>\nendobj\n4 "
        b"0 obj\n<<\n/Type /Catalog\n/Pages 1 0 R\n>>\nendobj\n5 0 obj\n<<\n/Type /Font\n/Subtype /Type1\n/Name"
        b" /F1\n/BaseFont /Helvetica\n/Encoding /WinAnsiEncoding\n>>\nendobj\n6 0 obj\n[ /PDF /Text"
        b" ]\nendobj\n7 0 obj\n<<\n/Length 1074\n>>\nstream\n2 J\r\nBT\r\n0 0 0 rg\r\n/F1 0027 Tf\r\n57.3750"
        b" 722.2800 Td\r\n( A Simple PDF File ) Tj\r\nET\r\nBT\r\n/F1 0010 Tf\r\n69.2500 688.6080 Td\r\n("
        b" This is a small demonstration .pdf file - ) Tj\r\nET\r\nBT\r\n/F1 0010 Tf\r\n69.2500 664.7040"
        b" Td\r\n( just for use in the Virtual Mechanics tutorials. More text. And more ) Tj\r\nET\r\nBT\r\n/F1"
        b" 0010 Tf\r\n69.2500 652.7520 Td\r\n( text. And more text. And more text. And more text. )"
        b" Tj\r\nET\r\nBT\r\n/F1 0010 Tf\r\n69.2500 628.8480 Td\r\n( And more text. And more text."
        b" And more text. And more text. And more ) Tj\r\nET\r\nBT\r\n/F1 0010 Tf\r\n69.2500 616.8960"
        b" Td\r\n( text. And more text. Boring, zzzzz. And more text. And more text. And )"
        b" Tj\r\nET\r\nBT\r\n/F1 0010 Tf\r\n69.2500 604.9440 Td\r\n( more text. And more text. And more"
        b" text. And more text. And more text. ) Tj\r\nET\r\nBT\r\n/F1 0010 Tf\r\n69.2500 592.9920 Td\r\n("
        b" And more text. And more text. ) Tj\r\nET\r\nBT\r\n/F1 0010 Tf\r\n69.2500 569.0880 Td\r\n( And"
        b" more text. And more text. And more text. And more text. And more ) Tj\r\nET\r\nBT\r\n/F1 0010"
        b" Tf\r\n69.2500 557.1360 Td\r\n( text. And more text. And more text. Even more. Continued on page"
        b" 2 ...) Tj\r\nET\r\n\nendstream\nendobj\nxref\n0 8\n0000000000 65535 f \n0000000009 00000 n"
        b" \n0000000068 00000 n \n0000000108 00000 n \n0000000251 00000 n \n0000000300 00000 n \n0000000407"
        b" 00000 n \n0000000437 00000 n \ntrailer\n<<\n/Size 8\n/Root 4 0 R\n/Info 2 0"
        b" R\n>>\nstartxref\n1563\n%%EOF\n"
    )

PUBTABNET_SAMPLE = {
    "imgid": 16,
    "html": {
        "cells": [
            {"tokens": ["<b>", "S", "u", "b", "n", "e", "t", "w", "o", "r", "k", "</b>"], "bbox": [11, 5, 60, 14]},
            {
                "tokens": [
                    "<b>",
                    "D",
                    "i",
                    "m",
                    "e",
                    "r",
                    " ",
                    "f",
                    "o",
                    "r",
                    "m",
                    "a",
                    "t",
                    "i",
                    "o",
                    "n",
                    "</b>",
                ],
                "bbox": [82, 5, 150, 14],
            },
            {
                "tokens": [
                    "<b>",
                    "M",
                    "o",
                    "n",
                    "o",
                    "m",
                    "e",
                    "r",
                    " ",
                    "b",
                    "i",
                    "n",
                    "d",
                    "i",
                    "n",
                    "g",
                    "</b>",
                ],
                "bbox": [175, 5, 245, 14],
            },
            {
                "tokens": ["<b>", "D", "i", "m", "e", "r", " ", "b", "i", "n", "d", "i", "n", "g", "</b>"],
                "bbox": [269, 5, 326, 14],
            },
            {
                "tokens": [
                    "<b>",
                    "M",
                    "u",
                    "l",
                    "t",
                    "i",
                    "p",
                    "l",
                    "e",
                    " ",
                    "e",
                    "q",
                    "u",
                    "i",
                    "l",
                    "i",
                    "b",
                    "r",
                    "i",
                    "a",
                    " ",
                    "r",
                    "u",
                    "l",
                    "e",
                    "d",
                    " ",
                    "o",
                    "u",
                    "t",
                    "?",
                    "</b>",
                ],
                "bbox": [362, 5, 475, 14],
            },
            {"tokens": []},
            {"tokens": []},
            {"tokens": []},
            {"tokens": []},
            {"tokens": ["<b>", "I", "G", "-", "T", "</b>"], "bbox": [343, 27, 363, 36]},
            {"tokens": ["<b>", "I", "G", "-", "K", "</b>"], "bbox": [376, 27, 396, 36]},
            {"tokens": ["<b>", "S", "R", "G", "</b>"], "bbox": [408, 27, 428, 36]},
            {"tokens": ["<b>", "I", "N", "J", "</b>"], "bbox": [439, 27, 454, 36]},
            {"tokens": ["<b>", "C", "R", "N", "T", "</b>"], "bbox": [467, 27, 493, 36]},
            {"tokens": ["<i>", "a", "b", "</i>"], "bbox": [31, 49, 41, 59]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [111, 49, 121, 59]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [205, 49, 215, 59]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [293, 49, 302, 59]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [348, 49, 359, 59]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [380, 49, 392, 59]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [412, 49, 424, 59]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [441, 49, 452, 59]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [474, 49, 486, 59]},
            {"tokens": ["<i>", "a", "b", "c", "d", "</i>"], "bbox": [27, 59, 44, 69]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [111, 59, 121, 69]},
            {"tokens": ["<i>", "y", "e", "s", "</i>", "<sup>", "+", "</sup>"], "bbox": [203, 59, 218, 69]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [293, 59, 302, 69]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [349, 59, 358, 69]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [381, 59, 391, 69]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [413, 59, 423, 69]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [442, 59, 451, 69]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [474, 59, 486, 69]},
            {"tokens": ["<i>", "a", "b", "c", "</i>"], "bbox": [29, 70, 42, 79]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [111, 70, 121, 79]},
            {"tokens": ["<i>", "y", "e", "s", "</i>", "<sup>", "-", "</sup>"], "bbox": [203, 70, 217, 79]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [293, 70, 302, 79]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [349, 70, 358, 79]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [381, 70, 391, 79]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [413, 70, 423, 79]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [441, 70, 452, 79]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [474, 70, 486, 79]},
            {"tokens": ["<i>", "a", "b", "e", "</i>"], "bbox": [29, 80, 42, 89]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [110, 80, 122, 89]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [205, 80, 215, 89]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [293, 80, 302, 89]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [349, 80, 358, 89]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [381, 80, 391, 89]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [412, 80, 424, 89]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [441, 80, 452, 89]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [474, 80, 486, 89]},
            {"tokens": ["<i>", "a", "b", "e", "f", "g", "</i>"], "bbox": [26, 90, 45, 100]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [110, 90, 122, 100]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [205, 90, 215, 100]},
            {"tokens": ["<i>", "y", "e", "s", "</i>", "<sup>", "+", "</sup>"], "bbox": [290, 90, 305, 100]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [349, 90, 358, 100]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [381, 90, 391, 100]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [413, 90, 423, 100]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [442, 90, 451, 100]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [475, 90, 485, 100]},
            {"tokens": ["<i>", "a", "b", "e", "f", "</i>"], "bbox": [28, 100, 44, 110]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [110, 100, 122, 110]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [205, 100, 215, 110]},
            {"tokens": ["<i>", "y", "e", "s", "</i>", "<sup>", "-", "</sup>"], "bbox": [291, 100, 304, 110]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [349, 100, 358, 110]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [381, 100, 391, 110]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [413, 100, 423, 110]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [441, 100, 452, 110]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [474, 100, 486, 110]},
            {"tokens": ["<i>", "a", "b", "c", "d", "e", "</i>"], "bbox": [26, 111, 46, 120]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [110, 111, 122, 120]},
            {"tokens": ["<i>", "y", "e", "s", "</i>", "<sup>", "+", "</sup>"], "bbox": [203, 111, 218, 120]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [293, 111, 302, 120]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [349, 111, 358, 120]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [381, 111, 391, 120]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [413, 111, 423, 120]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [442, 111, 451, 120]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [474, 111, 486, 120]},
            {"tokens": ["<i>", "a", "b", "c", "d", "e", "f", "g", "</i>"], "bbox": [23, 121, 49, 130]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [110, 121, 122, 130]},
            {"tokens": ["<i>", "y", "e", "s", "</i>", "<sup>", "+", "</sup>"], "bbox": [203, 121, 218, 130]},
            {"tokens": ["<i>", "y", "e", "s", "</i>", "<sup>", "+", "</sup>"], "bbox": [290, 121, 305, 130]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [349, 121, 358, 130]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [381, 121, 391, 130]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [413, 121, 423, 130]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [442, 121, 451, 130]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [475, 121, 485, 130]},
            {"tokens": ["<i>", "a", "b", "c", "d", "e", "f", "</i>"], "bbox": [24, 131, 47, 141]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [110, 131, 122, 141]},
            {"tokens": ["<i>", "y", "e", "s", "</i>", "<sup>", "+", "</sup>"], "bbox": [203, 131, 218, 141]},
            {"tokens": ["<i>", "y", "e", "s", "</i>", "<sup>", "-", "</sup>"], "bbox": [291, 131, 304, 141]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [349, 131, 358, 141]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [381, 131, 391, 141]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [413, 131, 423, 141]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [442, 131, 451, 141]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [474, 131, 486, 141]},
            {"tokens": ["<i>", "a", "b", "c", "e", "</i>"], "bbox": [27, 141, 44, 151]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [110, 141, 122, 151]},
            {"tokens": ["<i>", "y", "e", "s", "</i>", "<sup>", "-", "</sup>"], "bbox": [203, 141, 217, 151]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [293, 141, 302, 151]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [349, 141, 358, 151]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [381, 141, 391, 151]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [413, 141, 423, 151]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [441, 141, 452, 151]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [474, 141, 486, 151]},
            {"tokens": ["<i>", "a", "b", "c", "e", "f", "</i>"], "bbox": [26, 152, 45, 161]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [110, 152, 122, 161]},
            {"tokens": ["<i>", "y", "e", "s", "</i>", "<sup>", "-", "</sup>"], "bbox": [203, 152, 217, 161]},
            {"tokens": ["<i>", "y", "e", "s", "</i>", "<sup>", "-", "</sup>"], "bbox": [291, 152, 304, 161]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [349, 152, 358, 161]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [381, 152, 391, 161]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [413, 152, 423, 161]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [441, 152, 452, 161]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [474, 152, 486, 161]},
            {"tokens": ["<i>", "a", "b", "c", "e", "f", "g", "</i>"], "bbox": [25, 162, 47, 171]},
            {"tokens": ["<i>", "y", "e", "s", "</i>"], "bbox": [110, 162, 122, 171]},
            {"tokens": ["<i>", "y", "e", "s", "</i>", "<sup>", "-", "</sup>"], "bbox": [203, 162, 217, 171]},
            {"tokens": ["<i>", "y", "e", "s", "</i>", "<sup>", "+", "</sup>"], "bbox": [290, 162, 305, 171]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [349, 162, 358, 171]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [381, 162, 391, 171]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [413, 162, 423, 171]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [442, 162, 451, 171]},
            {"tokens": ["<i>", "n", "o", "</i>"], "bbox": [475, 162, 485, 171]},
        ],
        "structure": {
            "tokens": [
                "<thead>",
                "<tr>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td",
                ' colspan="5"',
                ">",
                "</td>",
                "</tr>",
                "<tr>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "</tr>",
                "</thead>",
                "<tbody>",
                "<tr>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "</tr>",
                "<tr>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "</tr>",
                "<tr>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "</tr>",
                "<tr>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "</tr>",
                "<tr>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "</tr>",
                "<tr>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "</tr>",
                "<tr>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "</tr>",
                "<tr>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "</tr>",
                "<tr>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "</tr>",
                "<tr>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "</tr>",
                "<tr>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "</tr>",
                "<tr>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "<td>",
                "</td>",
                "</tr>",
                "</tbody>",
            ]
        },
    },
    "split": "train",
    "filename": "PMC2759935_007_01.png",
}

PRODIGY_SAMPLE = {
    "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABEAAAAiCAIAAAA24aWuAAAAWElEQVQ4EZXBAQEAAAABIP6P"
    "zgZV5FTkVORU5FTkVORU5FTkVORU5FTkVORU5FTkVORU5FTkVORU5FTkVORU5FTkVORU5FTkVORU5FTkVORU5FTkVORU5DTzFG"
    "W9r8aRmwAAAABJRU5ErkJggg==",
    "text": "99999984_310518_J_1_150819_page_252.png",
    "spans": [
        {
            "label": "table",
            "x": 100,
            "y": 223.7,
            "w": 1442,
            "h": 1875.3,
            "type": "rect",
            "points": [[1, 2.7], [1, 29], [15, 29], [15, 2.7]],
        },
        {
            "label": "title",
            "x": 1181.6,
            "y": 99.2,
            "w": 364.6,
            "h": 68.8,
            "type": "rect",
            "points": [[11.6, 9.2], [11.6, 18], [16.2, 18], [16.2, 9.2]],
        },
    ],
    "_input_hash": -2030256107,
    "_task_hash": 1310891334,
    "_view_id": "image_manual",
    "width": 1650,
    "height": 2350,
    "answer": "reject",
}